language: rust
cache: cargo
matrix:
  include:
  - rust: stable
    env:
    - DANCE=OVER_ALL_THE_CRATES
    - RUST_BACKTRACE=full
    script: cargo test --all
  - rust: stable
    env: DANCE=DOCS_WALTZ
    before_script: curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git killercup/waltz --tag waltz_cli-0.1.4 --force
    script: docs/_test.sh
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - staging
    - trying
