[package]
name = "verbosity"
version = "0.1.0"
authors = ["Christopher Durham <cad97@cad97.com>"]
edition = "2018"

[dependencies]
quicli = "0.4"
structopt = "0.2"

[dev-dependencies]
assert_cli = "0.5.4"
